# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Windows

on:
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Install Vulkan SDK
          uses: humbletim/install-vulkan-sdk@v1.1.1
        - name: generate make files
          run: 
        - name: configure
          run: ./configure
        - name: make
          run: make
        - name: make check
          run: make check
        - name: make distcheck
          run: make distcheck
    